import React from 'react';
import { styled } from 'styled-components';
import { CodeStructureType } from '../types';
import { syntaxHighlight } from '../utils';

const ResultDetails = styled.details`
  margin-top: 4px;
  font-size: x-small;
`;

const ThoughtWrapper = styled.p`
  margin: 4px 0;
`;

const CodeStructureWrapper = styled.pre`
  background: #1a2638;
  color: #94a1b3;
  outline: 1px solid #ccc;
  padding: 5px;
  margin: 0 0 0.5rem 0;
`;

// @see https://dev.to/gauravadhikari1997/show-json-as-pretty-print-with-syntax-highlighting-3jpm
const CodeStyle = styled.code`
  font-family: source-code-pro, Menlo, Monaco, Consolas, 'Courier New', monospace;

  .string {
    color: green;
  }
  .number {
    color: darkorange;
  }
  .boolean {
    color: blue;
  }
  .null {
    color: magenta;
  }
  .key {
    color: red;
  }
`;

interface Props {
  codeStructure?: CodeStructureType;
  thoughtsWhenComposing: string;
};

const GeneratedResult: React.FC<Props> = ({
  codeStructure,
  thoughtsWhenComposing,
}) => {
    return (
      <>
        <ResultDetails>
          <summary>Here is the result generated by AI.</summary>
            <ThoughtWrapper> { thoughtsWhenComposing } </ThoughtWrapper>
            <CodeStructureWrapper>
              <CodeStyle
                dangerouslySetInnerHTML={{
                  __html: syntaxHighlight(JSON.stringify(codeStructure, undefined, 2))
                }}
              />
            </CodeStructureWrapper>
        </ResultDetails>
      </>
    );
  }

export default GeneratedResult;
